### ISSUE TITLE
Not an issue but a question.

### ISSUE THREAD

**Issue by natifygh** [ninjamuffin99/canabalt-hf#1]
Did you fully recode everything from the ground up or did you somehow just translate the as3 code to haxeflixel?

**Comment by ninjamuffin99** [comment]
Haxe has some roots from Actionscript 3, and HaxeFlixel of course is based off the Actionscript 3 framework!

So when porting, it was a bit of like translating from old english to new english. 

Actionscript 3 code that looks like this
```as3
 [Embed(source="../../../data/title.png")] private var ImgTitle:Class;
		
private var _title:FlxSprite;
		
override public function MenuState():void
{
	_title = new FlxSprite(ImgTitle,0,-FlxG.height);
	_title.velocity.y = 135;
	_title.drag.y = 60;
	add(_title);
```
Will get turned into Haxe code that looks like this

```hx
private var _title:FlxSprite;

override public function create()
{
        _title = new FlxSprite(0, -FlxG.height, "assets/images/title.png");
        _title.velocity.y = 135;
        _title.drag.y = 60;
        add(_title);
```

However there are some as3->haxe conversion tools out there! This one is by the HaxeFoundation! https://github.com/HaxeFoundation/as3hx
